spring.application.name: kafka-test

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: kafka-test
      auto-offset-reset: earliest

app:
  topic:
    name: test-kafka
    group-id: test-group
#

dd:
  trace:
    enabled: true
    analytics:
      enabled: true
    annotations: com.gaspar.kafka_test

management:
  endpoints:
    web:
      exposure:
        include: metrics, health
  datadog:
    metrics:
      export:
        apiKey: "dev_key"
        uri: ${DD_AGENT_HOST}
#        api-key: ${DD_API_KEY}
        # 172.27.0.1:8126/api/v1/series?api_key=
        step: "10s"
    service:
      kafka-test-gaspar
  metrics:
    tags:
      application: ${spring.application.name}
      env: dev

logging:
  level:
    datadig:
      trace: DEBUG
    root: DEBUG